<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>disable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <EnforceCodeStyleInBuild>True</EnforceCodeStyleInBuild>
	<EnableNETAnalyzers>True</EnableNETAnalyzers>
    <AnalysisLevel>latest</AnalysisLevel>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="external_components\**" />
    <EmbeddedResource Remove="external_components\**" />
    <None Remove="external_components\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Forms\edit_config-Surface-Patrick.cs" />
    <Compile Remove="Forms\Server-Surface-Patrick.cs" />
    <Compile Remove="Forms\server.Designer-Surface-Patrick.cs" />
    <Compile Remove="MainWindow-Surface-Patrick.cs" />
    <Compile Remove="Properties\Settings.Designer-Surface-Patrick.cs" />
    <Compile Remove="Utils-Surface-Patrick.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="App-Surface-Patrick.config" />
    <None Remove="databasev2-Surface-Patrick.db" />
    <None Remove="Properties\Settings-Surface-Patrick.settings" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentResults" Version="3.16.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.NetAnalyzers" Version="9.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="9.0.1" />
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlcipher" Version="2.1.10" />
    <PackageReference Include="SSH.NET" Version="2024.2.0" />
    <PackageReference Include="System.Formats.Asn1" Version="9.0.1" />
    <PackageReference Include="System.Security.Cryptography.OpenSsl" Version="5.0.0" />
    <PackageReference Include="System.Text.RegularExpressions" Version="4.3.1" />
    <PackageReference Include="System.Xml.ReaderWriter" Version="4.3.1" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Update="ApplicationSettings.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="images\ca.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="images\intermediate.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="images\server.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="images\user.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <!--<None Update="database.db">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>-->
    <!--<None Update="database.sqbpro">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>-->
    <!--<None Update="openssl-serve.cnf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>-->
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

</Project>